services:
  foundryvtt:
    image: ghcr.io/wrapped-owls/gontainer_foundryvtt:latest
    restart: unless-stopped
    #environment:
      #- FOUNDRY_RELEASE_URL=
    volumes:
      - ./data/foundry/data:/data
      - ./data/foundry/install:/foundry
    mem_reservation: 512m      # Soft limit
    mem_limit: 1600m            # Hard limit
    healthcheck:
      test: ["CMD", "foundryctl", "healthcheck"]
      interval: 30s
      timeout: 5s
      start_period: 3m
      retries: 3
    networks:
      - local-network

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SITE_ADDRESS=foundry.myhost_example.com
    depends_on:
      - foundryvtt
    volumes:
      - ./data/caddy/config:/config
      - ./data/caddy/data:/data
      - ./build/Caddyfile:/etc/caddy/Caddyfile:ro
    mem_reservation: 64m      # Soft limit
    mem_limit: 256m           # Hard limit
    networks:
      - local-network

networks:
  local-network:
